-- Seed Data Script for finAiPro
-- Creates Model table and populates defaults

CREATE TABLE IF NOT EXISTS "Model" (
    "id" TEXT PRIMARY KEY DEFAULT gen_random_uuid(),
    "agentId" TEXT,
    "name" TEXT NOT NULL,
    "architecture" TEXT NOT NULL,
    "accuracy" DOUBLE PRECISION DEFAULT 0,
    "fitness" DOUBLE PRECISION DEFAULT 0,
    "generation" INTEGER DEFAULT 1,
    "modelPath" TEXT,
    "optimizer" TEXT DEFAULT 'adam',
    "score" DOUBLE PRECISION DEFAULT 0,
    "createdAt" TIMESTAMPTZ DEFAULT now() NOT NULL,
    "updatedAt" TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- Template table for default agents
CREATE TABLE IF NOT EXISTS "SeedAgent" (
    "id" TEXT PRIMARY KEY DEFAULT gen_random_uuid(),
    "name" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "operationType" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "model" TEXT NOT NULL,
    "modelId" TEXT NOT NULL,
    "asset" TEXT NOT NULL,
    "assetId" TEXT NOT NULL,
    "assetType" TEXT NOT NULL,
    "prompt" TEXT,
    "tvSymbol" TEXT NOT NULL,
    "provider" TEXT NOT NULL,
    "timeframe" TEXT NOT NULL,
    "candleCount" INTEGER NOT NULL,
    "sources" TEXT,
    "predictionType" TEXT,
    "market" TEXT
);

DELETE FROM "SeedAgent";

-- Ensure Agent table has all columns required by Prisma and triggers
ALTER TABLE "Agent" ADD COLUMN IF NOT EXISTS "predictionType" TEXT DEFAULT 'swing';
ALTER TABLE "Agent" ADD COLUMN IF NOT EXISTS "isMultiPrediction" BOOLEAN DEFAULT false;
ALTER TABLE "Agent" ADD COLUMN IF NOT EXISTS "multiAssets" TEXT DEFAULT '';

INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('BTC Swing Trader', 'spot', 'market', 'active', 'GPT-4o', 'openai/gpt-4o', 'BTC', 'bitcoin', 'crypto', 'You are an expert Bitcoin swing trader. Analyze BTC/USDT using multi-timeframe analysis (4H and Daily). Consider: 1) Market structure and key S/R levels, 2) Moving averages (EMA 20, 50, 200), 3) RSI divergence, 4) Volume profile, 5) On-chain metrics from CoinGecko, 6) Fear & Greed Index. Provide precise entry, stop-loss (2-3% risk), and take-profit levels with 1:2.5 minimum risk-reward. Consider correlation with ETH and macro market conditions.', 'BTCUSDT', 'BINANCE', '240', 100, 'coingecko-news,coindesk', 'swing', 'crypto');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('ETH Scalper', 'spot', 'market', 'active', 'GPT-4o', 'openai/gpt-4o', 'ETH', 'ethereum', 'crypto', 'You are an Ethereum scalping specialist. Focus on 15-minute timeframe for quick entries. Use: 1) Order book analysis via volume clusters, 2) Bollinger Bands + RSI for overbought/oversold, 3) MACD crossovers, 4) BTC correlation for timing, 5) DeFi TVL trends from news sources. Target 0.5-1.5% moves with tight 0.3-0.5% stops. Best for high volatility periods. Consider gas fees and network activity.', 'ETHUSDT', 'BINANCE', '15', 50, 'coingecko-news,cointelegraph', 'scalping', 'crypto');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('SOL Trend Follower', 'spot', 'market', 'active', 'Claude 3.5', 'anthropic/claude-3.5-sonnet', 'SOL', 'solana', 'crypto', 'You are a Solana trend-following expert. Analyze SOL/USDT on 1H and 4H timeframes. Key factors: 1) Trend strength via ADX, 2) Parabolic SAR signals, 3) DApp activity and ecosystem growth, 4) TVL changes in Solana DeFi, 5) NFT market activity. Trade in direction of the main trend with trailing stops. Capture 5-15% moves. Monitor network performance and outages.', 'SOLUSDT', 'BINANCE', '60', 80, 'coindesk,decrypt', 'swing', 'crypto');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('XRP Breakout Hunter', 'spot', 'market', 'paused', 'GPT-4o', 'openai/gpt-4o', 'XRP', 'ripple', 'crypto', 'You are an XRP breakout specialist. Focus on identifying consolidation patterns and breakouts. Analyze: 1) Triangle and flag patterns, 2) Volume buildup before breakouts, 3) Regulatory news impact from SEC cases, 4) Ripple partnership announcements, 5) Cross-border payment adoption metrics. Set entries just above resistance with stops below the pattern. Target measured moves. Consider legal developments heavily.', 'XRPUSDT', 'BINANCE', 'D', 100, 'criptonoticias,cmc-sentiment', 'swing', 'crypto');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('BNB Momentum', 'spot', 'market', 'active', 'GPT-4o', 'openai/gpt-4o', 'BNB', 'binancecoin', 'crypto', 'You are a BNB momentum trader. Analyze BNB/USDT focusing on: 1) Binance ecosystem growth (Launchpad, Launchpool), 2) Token burn events and schedule, 3) BNB Chain activity and TVL, 4) Regulatory news affecting Binance, 5) Relative strength vs other exchange tokens. Use momentum indicators (RSI, Stochastic, MACD). Trade momentum bursts of 3-8%. Monitor exchange reserves and outflows.', 'BNBUSDT', 'BINANCE', '60', 60, 'coingecko-news', 'swing', 'crypto');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('DOGE Sentiment', 'spot', 'market', 'active', 'Claude 3.5', 'anthropic/claude-3.5-sonnet', 'DOGE', 'dogecoin', 'crypto', 'You are a Dogecoin sentiment-driven trader. Focus on: 1) Social media sentiment analysis from Twitter/X and Reddit, 2) Elon Musk mentions and influence, 3) Meme coin market cycles, 4) DOGE adoption news and partnerships, 5) Community activity and tipping culture. Trade sentiment spikes with quick exits. Be aware of high volatility and manipulation risks. Use sentiment as primary indicator.', 'DOGEUSDT', 'BINANCE', '60', 50, 'cmc-sentiment,cointelegraph', 'swing', 'crypto');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('ADA Technical', 'spot', 'market', 'active', 'GPT-4o', 'openai/gpt-4o', 'ADA', 'cardano', 'crypto', 'You are a Cardano long-term technical analyst. Perform deep analysis on ADA/USDT: 1) Elliott Wave counts, 2) Fibonacci retracements and extensions, 3) Cardano development milestones and hard forks, 4) Stake pool metrics and decentralization, 5) DeFi ecosystem growth on Cardano. Focus on larger timeframes (Daily/Weekly). Identify accumulation zones. Consider 6-12 month price targets.', 'ADAUSDT', 'BINANCE', '240', 100, 'coindesk,criptonoticias', 'long_term', 'crypto');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('AVAX Scalper', 'spot', 'market', 'active', 'GPT-4o', 'openai/gpt-4o', 'AVAX', 'avalanche', 'crypto', 'You are an Avalanche quick-scalping expert. Focus on 5-minute timeframe for ultra-fast trades. Use: 1) Level 2 order flow patterns, 2) VWAP bands, 3) Avalanche subnet launches and news, 4) DeFi yield opportunities on AVAX, 5) Gaming/NFT ecosystem developments. Target 0.3-0.8% quick scalps. Must act fast on breakouts. Consider network congestion and fees.', 'AVAXUSDT', 'BINANCE', '5', 30, 'decrypt,coingecko-news', 'scalping', 'crypto');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('LINK Swing Pro', 'spot', 'market', 'active', 'Claude 3.5', 'anthropic/claude-3.5-sonnet', 'LINK', 'chainlink', 'crypto', 'You are a professional Chainlink swing trader. Analyze LINK/USDT on 4H timeframe with focus on: 1) Oracle network adoption and partnerships (CCIP, Data Streams), 2) Staking v0.2 metrics, 3) LINK tokenomics and release schedule, 4) DeFi protocol integrations, 5) Smart contract platform correlations. Use swing high/low analysis with Fibonacci tools. Target 8-20% moves with strategic risk management.', 'LINKUSDT', 'BINANCE', '240', 80, 'cointelegraph,cmc-indicators', 'swing', 'crypto');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('DOT Long Term', 'spot', 'market', 'paused', 'GPT-4o', 'openai/gpt-4o', 'DOT', 'polkadot', 'crypto', 'You are a Polkadot long-term investment analyst. Analyze DOT on Weekly and Daily timeframes. Focus on: 1) Polkadot 2.0 roadmap progress, 2) Parachain auction results and lease expirations, 3) Cross-chain messaging (XCM) adoption, 4) Ecosystem project quality and TVL, 5) Governance proposals and treasury. Identify value zones for DCA accumulation. Consider 12-24 month holding periods. Focus on fundamentals over technicals.', 'DOTUSDT', 'BINANCE', 'D', 150, 'coindesk,criptonoticias', 'long_term', 'crypto');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('AAPL Swing Trader', 'spot', 'market', 'active', 'GPT-4o', 'openai/gpt-4o', 'AAPL', 'apple', 'stocks', 'You are an Apple stock swing trading specialist. Analyze AAPL on Daily and 4H charts. Key factors: 1) iPhone sales and product launch cycles, 2) Services revenue growth, 3) China market performance, 4) Vision Pro and new product adoption, 5) Warren Buffett/Berkshire positions, 6) Options flow and institutional activity. Use technical analysis with earnings calendar awareness. Trade around product announcements and earnings. Consider broader tech sector correlation (QQQ).', 'AAPL', 'NASDAQ', 'D', 100, 'bloomberg,reuters', 'swing', 'stocks');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('MSFT Trend Follower', 'spot', 'market', 'active', 'GPT-4o', 'openai/gpt-4o', 'MSFT', 'microsoft', 'stocks', 'You are a Microsoft trend analyst. Focus on: 1) Azure cloud growth vs AWS and GCP, 2) AI/Copilot revenue contribution, 3) Gaming division (Xbox, Activision), 4) LinkedIn performance, 5) Enterprise software adoption, 6) AI infrastructure investments. Trade with the primary trend using moving averages. Monitor quarterly earnings for trend confirmation. Consider dividend growth as support level indicator.', 'MSFT', 'NASDAQ', 'D', 80, 'cnbc,yahoo-finance', 'swing', 'stocks');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('GOOGL Breakout', 'spot', 'market', 'active', 'Claude 3.5', 'anthropic/claude-3.5-sonnet', 'GOOGL', 'google', 'stocks', 'You are a Google/Alphabet breakout trader. Analyze: 1) Search advertising revenue trends, 2) YouTube growth vs TikTok competition, 3) Google Cloud Platform market share, 4) AI/ Gemini developments and competition, 5) Regulatory risks (antitrust), 6) Pixel hardware sales. Identify consolidation patterns on 4H charts. Trade breakouts with volume confirmation. Watch for antitrust news impact.', 'GOOGL', 'NASDAQ', '240', 60, 'bloomberg,marketwatch', 'swing', 'stocks');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('AMZN Momentum', 'spot', 'market', 'active', 'GPT-4o', 'openai/gpt-4o', 'AMZN', 'amazon', 'stocks', 'You are an Amazon momentum trader. Focus on: 1) AWS cloud growth and margins, 2) E-commerce sales and Prime membership, 3) Advertising revenue growth, 4) Fulfillment network efficiency, 5) AI investments (Anthropic partnership), 6) Retail consumer spending trends. Trade momentum bursts on 1H timeframe. Monitor retail earnings seasons closely. Consider consumer sentiment indicators.', 'AMZN', 'NASDAQ', '60', 50, 'cnbc,reuters', 'swing', 'stocks');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('NVDA Scalper', 'spot', 'market', 'active', 'GPT-4o', 'openai/gpt-4o', 'NVDA', 'nvidia', 'stocks', 'You are an NVIDIA scalping expert for high-volatility trading. Key factors: 1) AI chip demand and data center revenue, 2) Gaming GPU sales, 3) Competition from AMD/Intel/custom chips, 4) Supply chain and TSMC capacity, 5) Options flow and institutional positioning, 6) AI infrastructure build-out news. Scalp on 15-minute timeframe. Use VWAP and level 2 data. High volatility requires tight risk management. Monitor AI-related news closely.', 'NVDA', 'NASDAQ', '15', 40, 'bloomberg,marketwatch', 'scalping', 'stocks');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('META Swing Pro', 'spot', 'market', 'paused', 'Claude 3.5', 'anthropic/claude-3.5-sonnet', 'META', 'meta', 'stocks', 'You are a Meta Platforms swing trader. Analyze: 1) Facebook/Instagram ad revenue, 2) Reels vs TikTok competition, 3) Reality Labs and Metaverse investments, 4) WhatsApp monetization, 5) AI Llama model developments, 6) Regulatory and privacy concerns. Trade on Daily timeframe with earnings awareness. Consider advertising market cycles. Watch for Reality Labs losses impact.', 'META', 'NASDAQ', 'D', 80, 'cnbc,yahoo-finance', 'swing', 'stocks');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('TSLA Volatility', 'spot', 'market', 'active', 'GPT-4o', 'openai/gpt-4o', 'TSLA', 'tesla', 'stocks', 'You are a Tesla volatility trader. Focus on: 1) EV delivery numbers and production, 2) FSD and autonomous driving progress, 3) Energy storage business growth, 4) Cybertruck production ramp, 5) Elon Musk and Twitter/X influence, 6) Competition from BYD and legacy automakers, 7) Margin pressure and price cuts. Trade high volatility with options awareness. 1H timeframe for entries. Consider sentiment extremes as reversal signals.', 'TSLA', 'NASDAQ', '60', 60, 'reuters,bloomberg', 'swing', 'stocks');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('JPM Dividend', 'spot', 'market', 'active', 'GPT-4o', 'openai/gpt-4o', 'JPM', 'jpmorgan', 'stocks', 'You are a JPMorgan Chase dividend and value investor. Analyze: 1) Interest rate environment and NII impact, 2) Investment banking fees and M&A activity, 3) Consumer banking and credit card trends, 4) Loan loss provisions and credit quality, 5) Regulatory capital requirements, 6) Dividend growth and buyback programs. Focus on long-term value on Weekly timeframe. Consider interest rate cycles. Target dividend growth and total return.', 'JPM', 'NYSE', 'D', 100, 'bloomberg,marketwatch', 'long_term', 'stocks');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('V Value Investor', 'spot', 'market', 'active', 'Claude 3.5', 'anthropic/claude-3.5-sonnet', 'V', 'visa', 'stocks', 'You are a Visa long-term value investor. Key factors: 1) Global payment volume growth, 2) Cross-border transaction recovery, 3) Competition from fintech and crypto payments, 4) Emerging market expansion, 5) Regulatory and interchange fee pressure, 6) Cash-to-digital conversion trends. Focus on Weekly timeframe for position building. Consider Warren Buffett holdings. Long-term compounder mindset.', 'V', 'NYSE', 'W', 50, 'yahoo-finance,cnbc', 'long_term', 'stocks');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('JNJ Stable Growth', 'spot', 'market', 'active', 'GPT-4o', 'openai/gpt-4o', 'JNJ', 'johnson', 'stocks', 'You are a Johnson & Johnson defensive investor. Analyze: 1) Pharmaceutical pipeline and drug approvals, 2) Medical device business growth, 3) Consumer health spinoff (Kenvue) impact, 4) Litigation risks (talc, opioid), 5) Dividend history and growth (Dividend King), 6) Healthcare sector trends. Focus on Weekly timeframe. Consider defensive positioning during market stress. Target stable dividend income with moderate growth.', 'JNJ', 'NYSE', 'D', 80, 'reuters,bloomberg', 'long_term', 'stocks');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('EUR/USD Swing', 'spot', 'market', 'active', 'GPT-4o', 'openai/gpt-4o', 'EUR/USD', 'eurusd', 'forex', 'You are an EUR/USD swing trading specialist. Analyze on 4H timeframe: 1) ECB vs Fed interest rate differentials, 2) Eurozone economic data (PMI, GDP, inflation), 3) US economic data (NFP, CPI, FOMC), 4) Dollar Index (DXY) correlation, 5) European sovereign bond spreads, 6) Geopolitical risk (Ukraine, energy). Use Fibonacci retracements and trend analysis. Consider central bank divergence. Trade around economic calendar events.', 'EURUSD', 'FX', '240', 100, 'forex-factory,dailyfx', 'swing', 'forex');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('GBP/USD Trend', 'spot', 'market', 'active', 'GPT-4o', 'openai/gpt-4o', 'GBP/USD', 'gbpusd', 'forex', 'You are a GBP/USD trend follower. Focus on: 1) Bank of England monetary policy, 2) UK inflation and economic growth, 3) Brexit implications and trade deals, 4) UK political stability, 5) Risk sentiment (Cable as risk proxy), 6) Cross-market correlations with UK equities. Trade Daily timeframe with trend-following indicators. Be aware of UK data volatility (London session). Consider GBP crosses for confirmation.', 'GBPUSD', 'FX', 'D', 80, 'investing-forex,dailyfx', 'swing', 'forex');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('USD/JPY Breakout', 'spot', 'market', 'active', 'Claude 3.5', 'anthropic/claude-3.5-sonnet', 'USD/JPY', 'usdjpy', 'forex', 'You are a USD/JPY breakout trader. Key factors: 1) Bank of Japan intervention risk, 2) Yield curve control policy, 3) US-Japan interest rate spread, 4) Japanese current account and trade balance, 5) Safe-haven flows (JPY as risk-off), 6) Nikkei correlation. Trade breakouts on 1H timeframe. Watch for intervention levels. Consider carry trade unwinding. Tokyo session volatility awareness.', 'USDJPY', 'FX', '60', 60, 'forex-factory,investing-forex', 'swing', 'forex');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('USD/CHF Scalper', 'spot', 'market', 'active', 'GPT-4o', 'openai/gpt-4o', 'USD/CHF', 'usdchf', 'forex', 'You are a USD/CHF scalping expert. Focus on: 1) SNB monetary policy, 2) EUR/CHF correlation, 3) Safe-haven flows to CHF, 4) Swiss economic data, 5) Gold price correlation, 6) Risk sentiment indicators. Scalp on 5-minute timeframe. Be aware of SNB intervention history. Tight spreads and quick execution. Consider cross-swiss pairs for context.', 'USDCHF', 'FX', '5', 40, 'dailyfx', 'scalping', 'forex');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('AUD/USD Momentum', 'spot', 'market', 'paused', 'GPT-4o', 'openai/gpt-4o', 'AUD/USD', 'audusd', 'forex', 'You are an AUD/USD momentum trader. Analyze: 1) RBA interest rate decisions, 2) China economic data (iron ore demand), 3) Commodity prices (iron ore, coal), 4) Australian housing market, 5) Risk sentiment (Aussie as risk proxy), 6) US-China trade relations. Trade momentum on 1H timeframe. Monitor China data releases closely. Consider commodity correlations.', 'AUDUSD', 'FX', '60', 50, 'forex-factory,investing-forex', 'swing', 'forex');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('USD/CAD Trend', 'spot', 'market', 'active', 'Claude 3.5', 'anthropic/claude-3.5-sonnet', 'USD/CAD', 'usdcad', 'forex', 'You are a USD/CAD trend trader (Loonie specialist). Key factors: 1) Bank of Canada policy, 2) Crude oil prices (WTI), 3) US-Canada trade relations, 4) Canadian housing market, 5) Economic data divergences, 6) Energy sector performance. Trade 4H timeframe with trend analysis. Oil price correlation is critical. Consider CAD crosses for confirmation.', 'USDCAD', 'FX', '240', 80, 'dailyfx,forex-factory', 'swing', 'forex');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('EUR/GBP Range', 'spot', 'market', 'active', 'GPT-4o', 'openai/gpt-4o', 'EUR/GBP', 'eurgbp', 'forex', 'You are an EUR/GBP range trading specialist. Focus on: 1) ECB-BoE policy divergence, 2) Brexit trade impact, 3) European vs UK economic data, 4) Range boundaries on Daily chart, 5) Stochastic for overbought/oversold, 6) Low volatility environment. Trade mean reversion within established ranges. 1H timeframe for entries. Be aware of breakout risks on major data.', 'EURGBP', 'FX', '60', 60, 'investing-forex', 'swing', 'forex');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('EUR/JPY Carry', 'spot', 'market', 'active', 'GPT-4o', 'openai/gpt-4o', 'EUR/JPY', 'eurjpy', 'forex', 'You are an EUR/JPY carry trade strategist. Analyze: 1) ECB-BOJ policy divergence, 2) Global risk sentiment, 3) Carry trade positioning, 4) Japanese investor flows to European bonds, 5) Volatility environment, 6) Cross-yen pairs correlation. Daily timeframe for position trades. Consider unwinding risks during risk-off. Target interest rate differential gains.', 'EURJPY', 'FX', 'D', 100, 'forex-factory,dailyfx', 'long_term', 'forex');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('NZD/USD Swing', 'spot', 'market', 'active', 'Claude 3.5', 'anthropic/claude-3.5-sonnet', 'NZD/USD', 'nzdusd', 'forex', 'You are a NZD/USD (Kiwi) swing trader. Focus on: 1) RBNZ policy decisions, 2) Dairy prices (Fonterra auction), 3) China-New Zealand trade, 4) Australian economy correlation, 5) Risk sentiment, 6) Housing market in NZ. Trade on 4H timeframe. Monitor dairy auction results. Consider AUD/NZD for relative strength.', 'NZDUSD', 'FX', '240', 70, 'investing-forex,dailyfx', 'swing', 'forex');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('EUR/AUD Breakout', 'spot', 'market', 'active', 'GPT-4o', 'openai/gpt-4o', 'EUR/AUD', 'euraud', 'forex', 'You are an EUR/AUD breakout specialist. Key factors: 1) ECB-RBA policy divergence, 2) European vs Australian economic data, 3) Commodity prices impact, 4) Risk sentiment swings, 5) Range consolidation patterns, 6) Volume confirmation. Trade breakouts on Daily timeframe. Consider EUR and AUD crosses separately. Be aware of commodity cycle impacts.', 'EURAUD', 'FX', 'D', 80, 'forex-factory', 'swing', 'forex');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('Gold Trend Follower', 'spot', 'market', 'active', 'GPT-4o', 'openai/gpt-4o', 'XAU', 'gold', 'commodities', 'You are a Gold trend-following expert. Analyze XAU/USD on Daily timeframe: 1) Real interest rates (TIPS yields), 2) DXY inverse correlation, 3) Central bank buying/selling, 4) Geopolitical risk premium, 5) ETF flows (GLD, IAU), 6) Physical demand (China, India). Use trend lines and moving averages. Consider safe-haven flows. Monitor Fed policy expectations closely.', 'GOLD', 'TVC', 'D', 100, 'kitco,investing-commodities', 'swing', 'commodities');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('Silver Momentum', 'spot', 'market', 'active', 'GPT-4o', 'openai/gpt-4o', 'XAG', 'silver', 'commodities', 'You are a Silver momentum trader. Focus on: 1) Gold-silver ratio for relative value, 2) Industrial demand (solar, EVs), 3) Photovoltaic industry growth, 4) Investment demand via ETFs, 5) Supply deficits/surpluses, 6) Dollar strength. Trade momentum on 4H timeframe. Higher volatility than gold. Consider both precious metal and industrial demand drivers.', 'SILVER', 'TVC', '240', 80, 'kitco,investing-commodities', 'swing', 'commodities');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('WTI Breakout', 'spot', 'market', 'active', 'Claude 3.5', 'anthropic/claude-3.5-sonnet', 'WTI', 'crude-oil', 'commodities', 'You are a WTI Crude Oil breakout trader. Key factors: 1) OPEC+ production decisions, 2) US shale production, 3) Global demand (China recovery), 4) US inventory data (EIA, API), 5) Geopolitical risks (Middle East, Russia), 6) Refining margins. Trade breakouts on Daily timeframe. Monitor weekly inventory reports. Consider Brent-WTI spread.', 'CL', 'NYMEX', 'D', 60, 'oilprice,investing-commodities', 'swing', 'commodities');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('Brent Trend', 'spot', 'market', 'active', 'GPT-4o', 'openai/gpt-4o', 'BRENT', 'brent-crude', 'commodities', 'You are a Brent Crude trend analyst. Focus on: 1) Global supply-demand balance, 2) OPEC+ compliance, 3) European/Asian demand, 4) North Sea production, 5) Shipping costs and routes, 6) Energy transition policies. Trade Daily timeframe with trend analysis. Brent as global benchmark. Monitor OPEC meetings closely.', 'BZ', 'NYMEX', 'D', 80, 'oilprice,investing-commodities', 'swing', 'commodities');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('Natural Gas Scalper', 'spot', 'market', 'paused', 'GPT-4o', 'openai/gpt-4o', 'NG', 'natural-gas', 'commodities', 'You are a Natural Gas scalping specialist. Key factors: 1) Weather forecasts (heating/cooling demand), 2) Storage reports (EIA Thursday), 3) LNG export levels, 4) Production levels, 5) Seasonal patterns (winter spike), 6) Power plant demand. Scalp on 15-minute timeframe during high volatility. Extreme weather awareness. Consider Henry Hub basis.', 'NG', 'NYMEX', '15', 40, 'investing-commodities', 'scalping', 'commodities');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('Copper Swing', 'spot', 'market', 'active', 'Claude 3.5', 'anthropic/claude-3.5-sonnet', 'CU', 'copper', 'commodities', 'You are a Copper swing trader (Dr. Copper). Analyze: 1) China economic data (PMI, construction), 2) Global manufacturing activity, 3) EV and renewable energy demand, 4) Chile/Peru supply issues, 5) Inventory levels (LME, COMEX), 6) US infrastructure spending. Trade Daily timeframe. China is the key driver. Consider copper-gold ratio for economic health.', 'HG', 'COMEX', 'D', 70, 'kitco,investing-commodities', 'swing', 'commodities');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('Wheat Long Term', 'spot', 'market', 'active', 'GPT-4o', 'openai/gpt-4o', 'WHEAT', 'wheat', 'commodities', 'You are a Wheat long-term analyst. Focus on: 1) Global supply (Russia, Ukraine, US), 2) Weather and crop conditions, 3) Black Sea geopolitical risks, 4) Export restrictions, 5) Food security concerns, 6) USDA reports (WASDE). Weekly timeframe for position trades. Consider seasonal harvest cycles. Monitor Northern Hemisphere growing seasons.', 'ZW', 'CBOT', 'W', 50, 'investing-commodities', 'long_term', 'commodities');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('Corn Trend', 'spot', 'market', 'active', 'GPT-4o', 'openai/gpt-4o', 'CORN', 'corn', 'commodities', 'You are a Corn trend trader. Key factors: 1) US corn belt weather, 2) Ethanol demand, 3) China import demand, 4) Brazil/Argentina competition, 5) USDA crop reports, 6) Livestock feed demand. Trade Daily timeframe. Planting and harvest seasons critical. Consider corn-soybean acreage competition.', 'ZC', 'CBOT', 'D', 80, 'investing-commodities', 'swing', 'commodities');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('Soybean Swing', 'spot', 'market', 'active', 'Claude 3.5', 'anthropic/claude-3.5-sonnet', 'SOY', 'soybeans', 'commodities', 'You are a Soybean swing trader. Focus on: 1) US-South America crop competition, 2) China import demand, 3) Crush margins and soybean oil demand, 4) Weather in Brazil and Argentina, 5) USDA reports, 6) Biofuel policies. Trade on 4H timeframe. Consider soy complex (meal, oil). Monitor South American growing season (Nov-Feb).', 'ZS', 'CBOT', '240', 60, 'investing-commodities', 'swing', 'commodities');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('Coffee Breakout', 'spot', 'market', 'active', 'GPT-4o', 'openai/gpt-4o', 'COFFEE', 'coffee', 'commodities', 'You are a Coffee breakout trader. Key factors: 1) Brazil weather (frost, drought), 2) Vietnam and Colombia production, 3) Global coffee consumption trends, 4) Currency movements (BRL), 5) Inventory levels, 6) Specialty vs commodity coffee trends. Trade breakouts on Daily timeframe. Weather scares create volatility. Consider arabica-robusta spread.', 'KC', 'ICE', 'D', 70, 'investing-commodities', 'swing', 'commodities');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('S&P 500 Swing', 'spot', 'market', 'active', 'GPT-4o', 'openai/gpt-4o', 'SPX', 'sp500', 'indices', 'You are an S&P 500 swing trader. Analyze on Daily timeframe: 1) Fed policy and interest rates, 2) Earnings season results, 3) Economic data (GDP, jobs, inflation), 4) Sector rotation patterns, 5) VIX and volatility regime, 6) Mag 7 concentration risk. Use technical analysis with macro overlay. Consider 200-day moving average as major level. Monitor breadth indicators.', 'SPX', 'TVC', 'D', 100, 'investing-indices,sp-global', 'swing', 'indices');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('Dow Jones Trend', 'spot', 'market', 'active', 'GPT-4o', 'openai/gpt-4o', 'DJI', 'dowjones', 'indices', 'You are a Dow Jones Industrial Average trend trader. Focus on: 1) Industrial and financial sector weightings, 2) Value vs growth rotation, 3) Interest rate sensitivity, 4) Component earnings (30 stocks), 5) Economic cycle indicators, 6) Blue-chip dividend yields. Trade Daily timeframe with trend-following indicators. Consider price-weighted nature of DJIA.', 'DJI', 'TVC', 'D', 80, 'investing-indices,sp-global', 'swing', 'indices');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('Nasdaq Tech', 'spot', 'market', 'active', 'Claude 3.5', 'anthropic/claude-3.5-sonnet', 'IXIC', 'nasdaq', 'indices', 'You are a Nasdaq 100 technology specialist. Analyze: 1) Tech earnings (NVDA, AAPL, MSFT, META), 2) AI investment cycle, 3) Interest rate impact on growth stocks, 4) Cloud and semiconductor trends, 5) IPO market activity, 6) Venture capital flows. Trade on 4H timeframe. Higher beta than SPX. Consider tech sector-specific news flow.', 'NAS100', 'TVC', '240', 60, 'investing-indices', 'swing', 'indices');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('Russell Small Cap', 'spot', 'market', 'paused', 'GPT-4o', 'openai/gpt-4o', 'RUT', 'russell2000', 'indices', 'You are a Russell 2000 small-cap trader. Key factors: 1) Economic cycle sensitivity, 2) Interest rates and borrowing costs, 3) Domestic US economy focus, 4) Value vs growth in small caps, 5) Recession risk indicator, 6) Regional bank exposure. Trade Daily timeframe. Small caps lead recoveries but suffer in downturns. Monitor relative strength vs large caps.', 'RUT', 'TVC', 'D', 80, 'investing-indices,sp-global', 'swing', 'indices');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('DAX 40 Germany', 'spot', 'market', 'active', 'GPT-4o', 'openai/gpt-4o', 'DAX', 'dax', 'indices', 'You are a DAX 40 German index trader. Focus on: 1) ECB monetary policy, 2) German manufacturing (PMI), 3) Energy costs and supply, 4) Auto sector performance, 5) Eurozone economic health, 6) Chemical industry. Trade Daily timeframe. Consider European session timing. Monitor German Ifo business climate.', 'DAX', 'TVC', 'D', 100, 'investing-indices', 'swing', 'indices');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('FTSE 100 UK', 'spot', 'market', 'active', 'Claude 3.5', 'anthropic/claude-3.5-sonnet', 'FTSE', 'ftse', 'indices', 'You are a FTSE 100 UK index trader. Key factors: 1) Bank of England policy, 2) Energy sector weighting (Shell, BP), 3) GBP impact on exporters, 4) Brexit aftermath, 5) UK political stability, 6) Mining sector exposure. Trade Daily timeframe. Consider currency impact on multinationals. Monitor UK economic data.', 'UK100', 'TVC', 'D', 80, 'investing-indices', 'swing', 'indices');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('CAC 40 France', 'spot', 'market', 'active', 'GPT-4o', 'openai/gpt-4o', 'CAC', 'cac', 'indices', 'You are a CAC 40 French index trader. Analyze: 1) Luxury goods sector (LVMH, Kering), 2) ECB policy impact, 3) French labor reforms, 4) Tourism and services, 5) Energy sector (Total), 6) European automotive. Trade on 4H timeframe. Consider luxury goods exposure. Monitor European economic indicators.', 'CAC', 'TVC', '240', 60, 'investing-indices', 'swing', 'indices');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('Nikkei 225 Japan', 'spot', 'market', 'active', 'GPT-4o', 'openai/gpt-4o', 'NIKKEI', 'nikkei', 'indices', 'You are a Nikkei 225 Japan index trader. Focus on: 1) Bank of Japan policy (yield curve control), 2) Yen strength impact on exporters, 3) Corporate governance reforms, 4) Tech and auto sectors, 5) Warren Buffett investments, 6) China economic relationship. Trade Daily timeframe. Consider USD/JPY correlation. Tokyo session timing awareness.', 'NI225', 'TVC', 'D', 100, 'investing-indices', 'swing', 'indices');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('Hang Seng HK', 'spot', 'market', 'active', 'Claude 3.5', 'anthropic/claude-3.5-sonnet', 'HSI', 'hangseng', 'indices', 'You are a Hang Seng Hong Kong index trader. Key factors: 1) China economic data, 2) Regulatory environment (tech, property), 3) HKD-USD peg stability, 4) Tech sector weighting (Alibaba, Tencent), 5) Property market crisis, 6) US-China tensions. Trade Daily timeframe. High volatility from China exposure. Monitor mainland policy closely.', 'HSI', 'TVC', 'D', 80, 'investing-indices', 'swing', 'indices');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('Euro Stoxx 50', 'spot', 'market', 'active', 'GPT-4o', 'openai/gpt-4o', 'SX5E', 'eurostoxx', 'indices', 'You are a Euro Stoxx 50 index trader. Analyze: 1) ECB monetary policy, 2) Eurozone GDP growth, 3) Energy costs and inflation, 4) Banking sector health, 5) Manufacturing PMI, 6) Individual country risks. Trade Daily timeframe. Pan-European exposure. Consider EUR/USD impact on returns.', 'SX5E', 'TVC', 'D', 70, 'investing-indices,sp-global', 'swing', 'indices');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('SPY S&P 500', 'spot', 'market', 'active', 'GPT-4o', 'openai/gpt-4o', 'SPY', 'spy', 'etfs', 'You are an SPY ETF trader. Focus on: 1) S&P 500 index tracking, 2) Pre-market and after-hours spreads, 3) Options flow and gamma exposure, 4) Sector rotation within SPY, 5) Flows vs VOO/IVV, 6) Dividend timing. Trade Daily timeframe. Consider bid-ask spreads and liquidity. Monitor SPY vs SPX basis.', 'SPY', 'AMEX', 'D', 100, 'etf-com,etfdb', 'swing', 'etfs');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('QQQ Nasdaq 100', 'spot', 'market', 'active', 'GPT-4o', 'openai/gpt-4o', 'QQQ', 'qqq', 'etfs', 'You are a QQQ ETF specialist. Analyze: 1) Nasdaq 100 composition (top holdings), 2) Magnificent 7 performance, 3) Tech sector earnings, 4) Growth vs value rotation, 5) Options activity, 6) Flows and AUM changes. Trade Daily timeframe. Higher beta than SPY. Consider QQQ vs QQQM for longer holds.', 'QQQ', 'NASDAQ', 'D', 80, 'etf-com,etfdb', 'swing', 'etfs');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('GLD Gold ETF', 'spot', 'market', 'active', 'Claude 3.5', 'anthropic/claude-3.5-sonnet', 'GLD', 'gld', 'etfs', 'You are a GLD gold ETF trader. Key factors: 1) Physical gold price tracking, 2) Real interest rates, 3) Dollar strength, 4) GLD vs physical gold spreads, 5) ETF creation/redemption, 6) Options activity. Trade Daily timeframe. Consider GLD vs IAU for cost efficiency. Monitor gold lease rates.', 'GLD', 'AMEX', 'D', 60, 'etf-com,etfdb', 'swing', 'etfs');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('IWM Russell', 'spot', 'market', 'active', 'GPT-4o', 'openai/gpt-4o', 'IWM', 'iwm', 'etfs', 'You are an IWM Russell 2000 ETF trader. Focus on: 1) Small-cap performance cycle, 2) Interest rate sensitivity, 3) Domestic economy exposure, 4) Recession indicator, 5) Relative strength vs SPY, 6) Regional bank exposure. Trade Daily timeframe. Consider IWM vs VTWO for cost efficiency. Monitor small-cap breadth.', 'IWM', 'AMEX', 'D', 80, 'etf-com,etfdb', 'swing', 'etfs');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('EEM Emerging', 'spot', 'market', 'paused', 'GPT-4o', 'openai/gpt-4o', 'EEM', 'eem', 'etfs', 'You are an EEM emerging markets ETF trader. Analyze: 1) China and India exposure, 2) Dollar strength impact, 3) Commodity prices, 4) Risk sentiment, 5) Local currency movements, 6) Country-specific risks. Trade Daily timeframe. Consider EEM vs VWO for cost efficiency. Monitor China policy closely.', 'EEM', 'AMEX', 'D', 70, 'etf-com', 'swing', 'etfs');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('VTI Total Market', 'spot', 'market', 'active', 'Claude 3.5', 'anthropic/claude-3.5-sonnet', 'VTI', 'vti', 'etfs', 'You are a VTI total market ETF investor. Focus on: 1) Broad US market exposure, 2) Market-cap weighted performance, 3) Long-term wealth building, 4) DCA strategies, 5) Sector allocation, 6) Economic cycle positioning. Weekly timeframe for position management. Lowest cost for broad exposure. Consider for core portfolio allocation.', 'VTI', 'AMEX', 'W', 50, 'etf-com,etfdb', 'long_term', 'etfs');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('TLT Treasury Bonds', 'spot', 'market', 'active', 'GPT-4o', 'openai/gpt-4o', 'TLT', 'tlt', 'etfs', 'You are a TLT 20+ year Treasury bond ETF trader. Key factors: 1) Federal Reserve policy, 2) Interest rate expectations, 3) Yield curve shape, 4) Inflation expectations, 5) Flight-to-quality flows, 6) Duration risk. Trade Daily timeframe. Inverse correlation with stocks often. Monitor FOMC meetings closely.', 'TLT', 'AMEX', 'D', 60, 'etf-com', 'swing', 'etfs');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('SLV Silver ETF', 'spot', 'market', 'active', 'GPT-4o', 'openai/gpt-4o', 'SLV', 'slv', 'etfs', 'You are an SLV silver ETF trader. Focus on: 1) Silver price tracking, 2) Industrial demand (solar, EV), 3) Gold-silver ratio, 4) Investment demand, 5) Supply dynamics, 6) Dollar strength. Trade Daily timeframe. Higher volatility than gold. Consider SLV vs physical silver premiums.', 'SLV', 'AMEX', 'D', 70, 'etf-com,etfdb', 'swing', 'etfs');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('VWO International', 'spot', 'market', 'active', 'Claude 3.5', 'anthropic/claude-3.5-sonnet', 'VWO', 'vwo', 'etfs', 'You are a VWO international ETF trader. Analyze: 1) Emerging and developed markets ex-US, 2) China exposure, 3) Currency movements, 4) Geopolitical risks, 5) Relative value vs US markets, 6) Economic cycles abroad. Trade Daily timeframe. Consider VWO vs EEM for cost efficiency. Monitor global economic divergence.', 'VWO', 'AMEX', 'D', 80, 'etf-com', 'swing', 'etfs');
INSERT INTO "SeedAgent" (name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", market) VALUES ('UVXY Volatility', 'spot', 'market', 'active', 'GPT-4o', 'openai/gpt-4o', 'UVXY', 'uvxy', 'etfs', 'You are a UVXY volatility ETF trader. CRITICAL WARNINGS: 1) Extreme decay from roll yield, 2) Only for short-term trading (hours to days), 3) VIX futures curve shape, 4) Spot VIX vs futures, 5) Market stress indicator, 6) Contango roll losses. Trade 1H timeframe ONLY. Never hold long-term. Use for hedging or speculation on volatility spikes. High risk of total loss.', 'UVXY', 'AMEX', '60', 50, 'etf-com,etfdb', 'scalping', 'etfs');

-- Sample Models (50 models)
DELETE FROM "Model";
INSERT INTO "Model" (name, architecture, accuracy, fitness, generation, score, optimizer) VALUES ('Model_001', 'Transformer-v2', 71.1, 0.81, 1, 57.591, 'adam');
INSERT INTO "Model" (name, architecture, accuracy, fitness, generation, score, optimizer) VALUES ('Model_002', 'Ensemble-X', 72.2, 0.82, 1, 59.204, 'adam');
INSERT INTO "Model" (name, architecture, accuracy, fitness, generation, score, optimizer) VALUES ('Model_003', 'GRN-Alpha', 73.3, 0.83, 1, 60.83899999999999, 'adam');
INSERT INTO "Model" (name, architecture, accuracy, fitness, generation, score, optimizer) VALUES ('Model_004', 'MiniMax-2.5', 74.4, 0.84, 1, 62.496, 'adam');
INSERT INTO "Model" (name, architecture, accuracy, fitness, generation, score, optimizer) VALUES ('Model_005', 'LSTM-v4', 75.5, 0.85, 1, 64.175, 'adam');
INSERT INTO "Model" (name, architecture, accuracy, fitness, generation, score, optimizer) VALUES ('Model_006', 'Transformer-v2', 76.6, 0.86, 1, 65.87599999999999, 'adam');
INSERT INTO "Model" (name, architecture, accuracy, fitness, generation, score, optimizer) VALUES ('Model_007', 'Ensemble-X', 77.7, 0.87, 1, 67.599, 'adam');
INSERT INTO "Model" (name, architecture, accuracy, fitness, generation, score, optimizer) VALUES ('Model_008', 'GRN-Alpha', 78.8, 0.88, 1, 69.344, 'adam');
INSERT INTO "Model" (name, architecture, accuracy, fitness, generation, score, optimizer) VALUES ('Model_009', 'MiniMax-2.5', 79.9, 0.89, 1, 71.111, 'adam');
INSERT INTO "Model" (name, architecture, accuracy, fitness, generation, score, optimizer) VALUES ('Model_010', 'LSTM-v4', 81.0, 0.9, 2, 72.9, 'adam');
INSERT INTO "Model" (name, architecture, accuracy, fitness, generation, score, optimizer) VALUES ('Model_011', 'Transformer-v2', 82.1, 0.91, 2, 74.711, 'adam');
INSERT INTO "Model" (name, architecture, accuracy, fitness, generation, score, optimizer) VALUES ('Model_012', 'Ensemble-X', 83.2, 0.92, 2, 76.54400000000001, 'adam');
INSERT INTO "Model" (name, architecture, accuracy, fitness, generation, score, optimizer) VALUES ('Model_013', 'GRN-Alpha', 84.3, 0.93, 2, 78.399, 'adam');
INSERT INTO "Model" (name, architecture, accuracy, fitness, generation, score, optimizer) VALUES ('Model_014', 'MiniMax-2.5', 85.4, 0.94, 2, 80.276, 'adam');
INSERT INTO "Model" (name, architecture, accuracy, fitness, generation, score, optimizer) VALUES ('Model_015', 'LSTM-v4', 86.5, 0.95, 2, 82.175, 'adam');
INSERT INTO "Model" (name, architecture, accuracy, fitness, generation, score, optimizer) VALUES ('Model_016', 'Transformer-v2', 87.6, 0.96, 2, 84.09599999999999, 'adam');
INSERT INTO "Model" (name, architecture, accuracy, fitness, generation, score, optimizer) VALUES ('Model_017', 'Ensemble-X', 88.7, 0.97, 2, 86.039, 'adam');
INSERT INTO "Model" (name, architecture, accuracy, fitness, generation, score, optimizer) VALUES ('Model_018', 'GRN-Alpha', 89.8, 0.98, 2, 88.00399999999999, 'adam');
INSERT INTO "Model" (name, architecture, accuracy, fitness, generation, score, optimizer) VALUES ('Model_019', 'MiniMax-2.5', 90.9, 0.99, 2, 89.991, 'adam');
INSERT INTO "Model" (name, architecture, accuracy, fitness, generation, score, optimizer) VALUES ('Model_020', 'LSTM-v4', 92.0, 0.8, 3, 73.60000000000001, 'adam');
INSERT INTO "Model" (name, architecture, accuracy, fitness, generation, score, optimizer) VALUES ('Model_021', 'Transformer-v2', 93.1, 0.81, 3, 75.411, 'adam');
INSERT INTO "Model" (name, architecture, accuracy, fitness, generation, score, optimizer) VALUES ('Model_022', 'Ensemble-X', 94.2, 0.82, 3, 77.244, 'adam');
INSERT INTO "Model" (name, architecture, accuracy, fitness, generation, score, optimizer) VALUES ('Model_023', 'GRN-Alpha', 95.3, 0.83, 3, 79.09899999999999, 'adam');
INSERT INTO "Model" (name, architecture, accuracy, fitness, generation, score, optimizer) VALUES ('Model_024', 'MiniMax-2.5', 96.4, 0.84, 3, 80.976, 'adam');
INSERT INTO "Model" (name, architecture, accuracy, fitness, generation, score, optimizer) VALUES ('Model_025', 'LSTM-v4', 72.5, 0.85, 3, 61.625, 'adam');
INSERT INTO "Model" (name, architecture, accuracy, fitness, generation, score, optimizer) VALUES ('Model_026', 'Transformer-v2', 73.6, 0.86, 3, 63.29599999999999, 'adam');
INSERT INTO "Model" (name, architecture, accuracy, fitness, generation, score, optimizer) VALUES ('Model_027', 'Ensemble-X', 74.7, 0.87, 3, 64.989, 'adam');
INSERT INTO "Model" (name, architecture, accuracy, fitness, generation, score, optimizer) VALUES ('Model_028', 'GRN-Alpha', 75.8, 0.88, 3, 66.704, 'adam');
INSERT INTO "Model" (name, architecture, accuracy, fitness, generation, score, optimizer) VALUES ('Model_029', 'MiniMax-2.5', 76.9, 0.89, 3, 68.441, 'adam');
INSERT INTO "Model" (name, architecture, accuracy, fitness, generation, score, optimizer) VALUES ('Model_030', 'LSTM-v4', 78.0, 0.9, 4, 70.2, 'adam');
INSERT INTO "Model" (name, architecture, accuracy, fitness, generation, score, optimizer) VALUES ('Model_031', 'Transformer-v2', 79.1, 0.91, 4, 71.981, 'adam');
INSERT INTO "Model" (name, architecture, accuracy, fitness, generation, score, optimizer) VALUES ('Model_032', 'Ensemble-X', 80.2, 0.92, 4, 73.784, 'adam');
INSERT INTO "Model" (name, architecture, accuracy, fitness, generation, score, optimizer) VALUES ('Model_033', 'GRN-Alpha', 81.3, 0.93, 4, 75.609, 'adam');
INSERT INTO "Model" (name, architecture, accuracy, fitness, generation, score, optimizer) VALUES ('Model_034', 'MiniMax-2.5', 82.4, 0.94, 4, 77.456, 'adam');
INSERT INTO "Model" (name, architecture, accuracy, fitness, generation, score, optimizer) VALUES ('Model_035', 'LSTM-v4', 83.5, 0.95, 4, 79.325, 'adam');
INSERT INTO "Model" (name, architecture, accuracy, fitness, generation, score, optimizer) VALUES ('Model_036', 'Transformer-v2', 84.6, 0.96, 4, 81.216, 'adam');
INSERT INTO "Model" (name, architecture, accuracy, fitness, generation, score, optimizer) VALUES ('Model_037', 'Ensemble-X', 85.7, 0.97, 4, 83.129, 'adam');
INSERT INTO "Model" (name, architecture, accuracy, fitness, generation, score, optimizer) VALUES ('Model_038', 'GRN-Alpha', 86.8, 0.98, 4, 85.064, 'adam');
INSERT INTO "Model" (name, architecture, accuracy, fitness, generation, score, optimizer) VALUES ('Model_039', 'MiniMax-2.5', 87.9, 0.99, 4, 87.021, 'adam');
INSERT INTO "Model" (name, architecture, accuracy, fitness, generation, score, optimizer) VALUES ('Model_040', 'LSTM-v4', 89.0, 0.8, 5, 71.2, 'adam');
INSERT INTO "Model" (name, architecture, accuracy, fitness, generation, score, optimizer) VALUES ('Model_041', 'Transformer-v2', 90.1, 0.81, 5, 72.981, 'adam');
INSERT INTO "Model" (name, architecture, accuracy, fitness, generation, score, optimizer) VALUES ('Model_042', 'Ensemble-X', 91.2, 0.82, 5, 74.78399999999999, 'adam');
INSERT INTO "Model" (name, architecture, accuracy, fitness, generation, score, optimizer) VALUES ('Model_043', 'GRN-Alpha', 92.3, 0.83, 5, 76.609, 'adam');
INSERT INTO "Model" (name, architecture, accuracy, fitness, generation, score, optimizer) VALUES ('Model_044', 'MiniMax-2.5', 93.4, 0.84, 5, 78.456, 'adam');
INSERT INTO "Model" (name, architecture, accuracy, fitness, generation, score, optimizer) VALUES ('Model_045', 'LSTM-v4', 94.5, 0.85, 5, 80.325, 'adam');
INSERT INTO "Model" (name, architecture, accuracy, fitness, generation, score, optimizer) VALUES ('Model_046', 'Transformer-v2', 95.6, 0.86, 5, 82.216, 'adam');
INSERT INTO "Model" (name, architecture, accuracy, fitness, generation, score, optimizer) VALUES ('Model_047', 'Ensemble-X', 96.7, 0.87, 5, 84.129, 'adam');
INSERT INTO "Model" (name, architecture, accuracy, fitness, generation, score, optimizer) VALUES ('Model_048', 'GRN-Alpha', 97.8, 0.88, 5, 86.064, 'adam');
INSERT INTO "Model" (name, architecture, accuracy, fitness, generation, score, optimizer) VALUES ('Model_049', 'MiniMax-2.5', 98.9, 0.89, 5, 88.021, 'adam');
INSERT INTO "Model" (name, architecture, accuracy, fitness, generation, score, optimizer) VALUES ('Model_050', 'LSTM-v4', 75.0, 0.9, 6, 67.5, 'adam');

-- Trigger to initialize new user profiles with default agents
CREATE OR REPLACE FUNCTION initialize_user_agents()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO "Agent" ("userId", name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, "tvSymbol", provider, timeframe, "candleCount", sources, "predictionType", "isMultiPrediction", "multiAssets")
    SELECT NEW."id", name, type, "operationType", status, model, "modelId", asset, "assetId", "assetType", prompt, tvSymbol, provider, timeframe, "candleCount", sources, "predictionType", false, ''
    FROM "SeedAgent";
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS tr_initialize_user_agents ON "Profile";
CREATE TRIGGER tr_initialize_user_agents
AFTER INSERT ON "Profile"
FOR EACH ROW
EXECUTE FUNCTION initialize_user_agents();